### PR TITLE
[Hunter] Extend DeathTracker to ignore Feign Death casts as deaths

### LINKED ISSUE #2670: [Hunter] Wrong death statistic
Whenever a hunter uses feign death, it will incorrectly register as time spent dead - however there is no cast event for feign death. 

My idea is to lower timespent dead whenever the hunter is dead for less than 1second.

### PR DESCRIPTION
**Pull request by Pewtro**
Blocked by #3611 
Fixes #2670 

Due to combatlog restrictions, Feign Death is not shown as a cast event to other players (to make it more believable, otherwise it is cheesable with WA/AddOns easier than already). 
This change ignores extremely short deaths for hunters. 

Log: 
Before: 
image
After:
No suggestion

Log: 
Before:
image

After:
image

### CODE REVIEW

File: src/parser/hunter/shared/modules/core/DeathTracker.tsx [hunk 1]
```diff
@@ -0,0 +1,32 @@
+import CoreDeathTracker from 'parser/shared/modules/DeathTracker';
+
+
+/**
+ * Due to combatlog restrictions it is not possible to know whether the hunter cast Feign Death or the hunter actually died.
+ * For this module we assume any single death lasting less than 0.2% of an encounter (1.2 seconds on a 10 minute fight) was due to Feign Death, and thus we remove it as it is improbable anyone is that fast to ress anyone.
+ */
+const TIME_SPENT_DEAD_THRESHOLD = 0.002; //0.2%
+// @ts-ignore duplicate indicator, but it's extended just like other modules
+class DeathTracker extends CoreDeathTracker {
```
Comment (Pewtro) [inline src/parser/hunter/shared/modules/core/DeathTracker.tsx:10]: I'm really confused about this ts-ignore, and I don't know why it's necessary - but it kept insisting there was a duplicate identifier..
image
