### PR TITLE
Bugfix/te fixes

### LINKED ISSUE #5780: TwilightEquilibrium

### LINKED ISSUE #5781: - Investigate TE talents (https://wowanalyzer.com/report/VqfDALwzF14PCK6t/23-Normal+Dathea,+Ascended+-+Kill+(6:03)/Heal%C3%ACnc/standard/statistics) based on this log

### PR DESCRIPTION
**Pull request by oisinod**
### Description

Fixed bugs relating to damage spells and their travel time not linking with TE properly.

### Testing

- Screenshot(s):
image

closes #5781 
closes #5780

### CODE REVIEW

File: src/analysis/retail/priest/discipline/CONFIG.tsx [hunk 1]
```diff
@@ -35,7 +35,7 @@ const config: Config = {
     </>
   ),
   // A recent example report to see interesting parts of the spec. Will be shown on the homepage.
-  exampleReport: '/report/TGzmk4bXDZJndpj7/6-Heroic+Opulence+-+Kill+(8:12)/16-Gabethedark',
+  exampleReport: '',
```
Comment (emallson) [inline src/analysis/retail/priest/discipline/CONFIG.tsx]: if you're setting patch compat you should put a report link here

File: src/analysis/retail/priest/discipline/modules/spells/TwilightEquilibrium/TwilightEquilibrium.tsx [hunk 2]
```diff
@@ -44,59 +54,79 @@ class TwilightEquilibrium extends Analyzer {
...
-    if (HOLY_DAMAGE_SPELLS.includes(damageEvent?.ability.guid ?? -1)) {
-      this.handleHolyHeal(event);
-    }
-
-    if (SHADOW_DAMAGE_SPELLS.includes(damageEvent?.ability.guid ?? -1)) {
-      this.handleShadowHeal(event);
+    if (this.checkDamageEvent(damageEvent)) {
+      if (damageEvent.ability.guid === TALENTS_PRIEST.SCHISM_TALENT.id) {
+        console.log(calculateEffectiveHealing(event, TE_INCREASE), event);
+      }
```
Comment (emallson) [inline src/analysis/retail/priest/discipline/modules/spells/TwilightEquilibrium/TwilightEquilibrium.tsx]: stray console.log
```suggestion
```

File: src/analysis/retail/priest/discipline/normalizers/DamageCastLink.ts [hunk 3]
```diff
@@ -0,0 +1,112 @@
...
+      // If the cast and damage event have different IDs, check that the IDs match
+      const damageEvent = linkingEvent as DamageEvent;
+      const castEvent = referencedEvent as CastEvent;
+
+      // If the cast and damage event have different IDs, check that the IDs match (Some spells have different IDs for the cast and damage events)
+      if (SPELLS_WITH_DIFFERENT_CAST_AND_DAMAGE_IDS[castEvent.ability.guid]) {
+        if (
+          SPELLS_WITH_DIFFERENT_CAST_AND_DAMAGE_IDS[castEvent.ability.guid] !==
+          damageEvent.ability.guid
+        ) {
```
Comment (emallson) [inline src/analysis/retail/priest/discipline/normalizers/DamageCastLink.ts:77]:
```suggestion
      if (SPELLS_WITH_DIFFERENT_CAST_AND_DAMAGE_IDS[castEvent.ability.guid] && SPELLS_WITH_DIFFERENT_CAST_AND_DAMAGE_IDS[castEvent.ability.guid] !== damageEvent.ability.guid) {
```

(will need to re-run prettier after applying suggestion if you do so with github)

**Review by emallson — CHANGES_REQUESTED** [review]
very minor stuff then mergable
