### PR TITLE
Vdh general updates

### LINKED ISSUE #4842: [VDH] [Talents] Agonizing Flames
fairly certain this talent is implemented wrong / outdated

its currently checking both initial hit damage as well as periodical hits while its up and then assumes a flat 20% buff which looks like this version:
image

the talent in its current fashion increases its duration by 50%:
image

ill file a pr later to adress this. 

things to respect:
- [x] recasting before base duration must be considered
- [ ] growing inferno conduit presence is relevant (damage calc should be based on not having growing inferno, although its bis)

### PR DESCRIPTION
**Pull request by ljosberinn**
- fixes #4842

and uh a handful of other things:
- enabled Growing Inferno for VDH too since it was already present for havoc
- added Shattered Restoration
- added Repeat Decree
- add capstone trait detection to be used for `Combatant.likelyHasEmpoweredConduits()` method

image

### CODE REVIEW

File: src/parser/core/Combatant.ts [hunk 1]
```diff
@@ -279,6 +280,14 @@ class Combatant extends Entity {
     return this.conduitsByConduitID[spellId] && this.conduitsByConduitID[spellId].rank;
   }
 
+  likelyHasEmpoweredConduits() {
```
Comment (Pewtro) [inline src/parser/core/Combatant.ts:287]: I think it'd be worth to call this function in the conduitRankBySpellID function and return rank + 2 if true, otherwise just rank. That ensures that the individual contributor has to do as little as possible to support empowered conduits.

File: analysis/demonhuntervengeance/src/modules/shadowlands/conduits/ShatteredRestoration.tsx [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+
+    if (!this.active) {
+      return;
+    }
+
+    const rank = this.selectedCombatant.conduitRankBySpellID(SPELLS.SHATTERED_RESTORATION.id);
+    this.rank = rank;
+    // rank 1 = 5%, scaling up to rank 11 atm at 10%
+    this.factor =
+      (this.selectedCombatant.likelyHasEmpoweredConduits() ? 0.06 : 0.05) + (rank - 1) * 0.005;
```
Comment (Pewtro) [inline analysis/demonhuntervengeance/src/modules/shadowlands/conduits/ShatteredRestoration.tsx]: If you want to, you could do something similiar to what has been done in analysis\hunterbeastmastery\src\constants.ts & analysis\hunterbeastmastery\src\modules\spells\conduits\Bloodletting.tsx using the generated spell scaling information relative to the rank rather than rely on calculating it yourself.

File: analysis/demonhunter/src/shadowlands/conduits/GrowingInferno.tsx [hunk 3]
```diff
@@ -29,7 +29,11 @@ class GrowingInferno extends Analyzer {
       return;
     }
 
-    this.conduitRank = this.selectedCombatant.conduitRankBySpellID(SPELLS.GROWING_INFERNO.id);
+    const empoweredConduitsRankOffset = this.selectedCombatant.likelyHasEmpoweredConduits() ? 2 : 0;
+
+    this.conduitRank =
+      this.selectedCombatant.conduitRankBySpellID(SPELLS.GROWING_INFERNO.id) +
+      empoweredConduitsRankOffset;
```
Comment (Pewtro) [inline analysis/demonhunter/src/shadowlands/conduits/GrowingInferno.tsx]: If you alter the conduitRankBySpellID this offset can be removed

File: src/parser/core/Combatant.ts [hunk 4]
```diff
@@ -276,8 +276,12 @@ class Combatant extends Entity {
     return Boolean(this.conduitsByConduitID[spellId]);
   }
 
-  conduitRankBySpellID(spellId: number) {
-    return this.conduitsByConduitID[spellId] && this.conduitsByConduitID[spellId].rank;
+  conduitRankBySpellID(spellId: number): number {
+    if (!(spellId in this.conduitRankBySpellID)) {
+      return 0;
```
Comment (ljosberinn) [inline src/parser/core/Combatant.ts:281]: this is now a slight behaviour change. previously it would return `undefined`:

```js
const conduitsByConduitID = {
    1: {
        rank: 2
    }
}

conduitsByConduitID[2] && conduitsByConduitID[2].rank // undefined
conduitsByConduitID[1] && conduitsByConduitID[1].rank // 2
```

this error was however uncaught, ts happily thought its a `number` either way...

File: src/parser/core/Combatant.ts [hunk 5]
```diff
@@ -276,8 +276,12 @@ class Combatant extends Entity {
     return Boolean(this.conduitsByConduitID[spellId]);
   }
 
-  conduitRankBySpellID(spellId: number) {
-    return this.conduitsByConduitID[spellId] && this.conduitsByConduitID[spellId].rank;
+  conduitRankBySpellID(spellId: number): number {
+    if (!(spellId in this.conduitRankBySpellID)) {
```
Comment (Pewtro) [inline src/parser/core/Combatant.ts]: this.conduitRankBySpellID doesn't seem right, did you mean conduitsByConduitId

Comment (ljosberinn) [reply src/parser/core/Combatant.ts]: 🤫

**Comment by Pewtro** [comment]
If you could include a core changelog entry about assuming empowered with capstone since it's a larger change, that'd be awesome. 

You will also need to update some snapshot tests as you're changing all conduit modules with this PR indirectly

**Comment by ljosberinn** [comment]
the magefire snapshot works locally, I'm not seeing any diffs in snapshots there 🤔 (except `,` changing to `.` in formatting)

File: src/parser/core/Combatant.ts (hunk 4 above)
Comment (emallson) [reply src/parser/core/Combatant.ts:281]: would honestly prefer this to return undefined, but i know we've had errors pop up related to this and that TS didn't catch it means that I'd be spooked about switching the return type.

which is to say, this change seems okay to me (especially since this goes away entirely for 10.0 :smiley:)

**Comment by Sharrq** [comment]
> the magefire snapshot works locally, I'm not seeing any diffs in snapshots there 🤔 (except `,` changing to `.` in formatting)

I updated the tests for fire about an hour or two ago, so you might just need to update from the shadowlands branch to get the new integration test

**Comment by ljosberinn** [comment]
> If you could include a core changelog entry about assuming empowered with capstone since it's a larger change, that'd be awesome.

which changelog file would this core entry go to?

edit: found it, am blind

File: analysis/demonhuntervengeance/src/modules/shadowlands/legendaries/BlindFaith.tsx [hunk 6]
```diff
@@ -60,12 +99,71 @@ export default class BlindFaith extends Analyzer {
...
+      this.dataset[prevStacks].end = event.timestamp;
+    }
+
+    this.dataset[nextStacks] = { start: event.timestamp, end: 0 };
   }
 
-  statistic() {
-    const avg = Math.round(
-      this.stacksGained.reduce((acc, stacks) => acc + stacks, 0) / this.stacksGained.length,
+  goodWindowsPercentage = 0;
```
Comment (Pewtro) [inline analysis/demonhuntervengeance/src/modules/shadowlands/legendaries/BlindFaith.tsx]: I doubt this is correct? 

Also it's hard to review this if more features unrelated to existing PR keeps piling on after every review :(

File: analysis/demonhuntervengeance/src/modules/shadowlands/legendaries/BlindFaith.tsx [hunk 7]
```diff
@@ -60,12 +99,71 @@ export default class BlindFaith extends Analyzer {
...
+
+  get suggestionThresholdsEfficiency() {
+    return {
+      actual: this.goodWindowsPercentage,
+      isLessThan: {
+        minor: 0.65,
+        average: 0.75,
+        major: 0.5,
```
Comment (emallson) [inline analysis/demonhuntervengeance/src/modules/shadowlands/legendaries/BlindFaith.tsx:128]: this looks wrong---should either be minor > average > major or minor < average < major. this is minor > major and minor < average.

Comment (ljosberinn) [reply analysis/demonhuntervengeance/src/modules/shadowlands/legendaries/BlindFaith.tsx:128]: oh then I misinterpreted how its supposed to work, I thought its intended to be average > minor > major, makes sense

Comment (emallson) [reply analysis/demonhuntervengeance/src/modules/shadowlands/legendaries/BlindFaith.tsx:128]: they might be better named as:

- minor: nitpick
- average: minor problem
- major: major problem

but they're not :P

File: analysis/demonhuntervengeance/src/modules/shadowlands/legendaries/BlindFaith.tsx (hunk 6 above)
Comment (ljosberinn) [reply analysis/demonhuntervengeance/src/modules/shadowlands/legendaries/BlindFaith.tsx]: > I doubt this is correct?

what should it be, a getter fn? I've loosely based this on spirit bomb and didnt look around tooooo much for this one tbh

> Also it's hard to review this if more features unrelated to existing PR keeps piling on after every review :(Also it's hard to review this if more features unrelated to existing PR keeps piling on after every review :(

sorry, had a burst of productivity in a sleepless night there, further stuff will def be split up
