### PR TITLE
[Core] fixes eonar bug with not all regular procs accounted for

### LINKED ISSUE #1394: [General] Not all Eonar's procs accounted for.
In this [log](https://www.warcraftlogs.com/reports/qD6arnA8ZFmTykMJ) Sou had 14 regular healing procs and the [analyzer](https://wowanalyzer.com/report/qD6arnA8ZFmTykMJ/19-Mythic+Kin'garoth+-+Kill+(7:47)/3-Sou) only picks up 10.

### PR DESCRIPTION
**Pull request by Pewtro**
image

fixes #1394 

log: https://www.warcraftlogs.com/reports/qD6arnA8ZFmTykMJ#fight=last&source=3&type=auras

### CODE REVIEW

File: src/Parser/Core/Modules/Items/Legion/AntorusTheBurningThrone/EonarsCompassion.js [hunk 1]
```diff
@@ -83,6 +83,14 @@ class EonarsCompassion extends Analyzer {
     }
   }
 
+  //if the regular proc procs again while it's already active
+  on_byPlayer_refreshbuff(event) {
+    const spellId = event.ability.guid;
+    if (spellId === SPELLS.EONARS_COMPASSION_PROCBUFF.id || this.triggerBuffs.includes(spellId)) {
```
Comment (Gebuz) [inline src/Parser/Core/Modules/Items/Legion/AntorusTheBurningThrone/EonarsCompassion.js]: isn't triggerBuffs the pantheon buffs? I'd assume it should just look like `on_byPlayer_applybuff(event)`

Comment (Pewtro) [reply src/Parser/Core/Modules/Items/Legion/AntorusTheBurningThrone/EonarsCompassion.js]: Fixed heh
