### PR TITLE
All Gems Showing fix

### LINKED ISSUE #7336: Character Screen only showing 1 gem per Slot
The character screen is only showing 1 gem when multiple are socketed.

This is what is showing in the Preparation Section for the new Gems portion:
Image

This is what shows on the Character Screen:
Image

Comparing with the Tooltip from the Character Screen.

Image

Only 1 of the gems is showing.

I like to look into this as I have an idea for an enhancement around this area and be good to get my feet wet in the code.

### PR DESCRIPTION
**Pull request by CericME**
### Description
Fixes  WoWAnalyzer/WoWAnalyzer#7336

Essentially this PR the gems showing in the gear area of the character screen match what in the gem subsection of the preparation section.

To make the empty socket work I needed a socket item.  As the item is used like a gem in WowAnalyzer I put the empty socket item in the gem section.  As ItemId is a number which is signed I made the ItemId a negative number to indicate that this is not a blizzard provided item.  This is a very niche case.  I wanted to do something that could be mimicked by the next time such a niche case shows up. (Colored socket support, possibly.)  The number is -818 because it was 8:18 when I put the property in and should avoid any random test ones.

Note for anyone working in this area.  The grid that is used is brittle.

### Testing

Put in a report and go to the character section.

- Test report URL: `/report/...`
Current:
https://wowanalyzer.com/report/kjC2zFbXKwvdfaxh/17-Heroic+Chrome+King+Gallywix+-+Wipe+16+(9:26)/Locsul/standard/character
image

Fix:
http://localhost:3000/report/kjC2zFbXKwvdfaxh/17-Heroic+Chrome+King+Gallywix+-+Wipe+16+(9:26)/Locsul/standard/character
image

Current:
https://wowanalyzer.com/report/2FJ7rKkVbDz3hdfg/39-Normal+Vexie+and+the+Geargrinders+-+Kill+(2:19)/Auhken/standard/character
image

Fixed:
http://localhost:3000/report/2FJ7rKkVbDz3hdfg/39-Normal+Vexie+and+the+Geargrinders+-+Kill+(2:19)/Auhken/standard/character
image

### CODE REVIEW

File: src/interface/report/Results/PlayerInfoGems.tsx [hunk 1]
```diff
@@ -1,24 +1,68 @@
...
+
+  for (; i < actualSocketCount; i += 1) {
+    result.push({
+      gem: {
+        id: -818,
+        icon: 'equipment_empty_gem_socket',
+        itemLevel: -1,
+      },
+    });
+  }
```
Comment (emallson) [inline src/interface/report/Results/PlayerInfoGems.tsx]: since this was added to `ITEMS`, use `ITEMS.EMPTY_GEM_SOCKET`.

File: src/common/ITEMS/thewarwithin/gems.ts [hunk 2]
```diff
@@ -553,6 +553,13 @@ const gems = {
     icon: 'inv_misc_epicgem_01',
     craftQuality: 1,
   },
+  EMPTY_GEM_SOCKET: {
+    //In this codebase everywhere this needs to be used is the same as a gem
+    id: -818, //Number is signed taking advantage of that to mark pseudo items
```
Comment (emallson) [inline src/common/ITEMS/thewarwithin/gems.ts:558]: i don't love this but i don't have a better suggestion.

File: src/interface/report/Results/PlayerInfoGems.tsx [hunk 3]
```diff
@@ -1,24 +1,68 @@
...
+import {
+  eventItemGemSocketCount,
+  eventItemHasGemSocket,
+} from 'common/ITEMS/thewarwithin/socketBonusId';
 
 interface Props {
   gear: Item[];
 }
 
+function buildGemPlaceholders(item: Item): { gem: EventGem }[] {
```
Comment (emallson) [inline src/interface/report/Results/PlayerInfoGems.tsx]: this is duplicated from `GemChecker`. could refactor it into the `socketBonusId` file and then use it as a method within `GemChecker` like:

```ts
  buildGemPlaceholders(item: EventItem, slotNumber: number): { gem: EventGem }[] {
    const actualSocketCount: number = eventItemGemSocketCount(item);
    const maxSockets: number = this.maxSocketCount(slotNumber, true);
    const socketAddingItemId: number | undefined = this.GemableSlots[slotNumber]?.socketingItemId;

    const result: { gem: EventGem }[] = buildGemPlaceholders(item);

    // <insert socketAddingItemId loop>

    return result;
  }
```

**Review by emallson — COMMENTED** [review]
seems mostly fine. some minor refactoring suggestions. otherwise can be merged

File: src/common/ITEMS/thewarwithin/gems.ts (hunk 2 above)
Comment (CericME) [reply src/common/ITEMS/thewarwithin/gems.ts:558]: I don't love it either but the alternatives were starting to get worse.

File: src/interface/report/Results/PlayerInfoGems.tsx (hunk 1 above)
Comment (CericME) [reply src/interface/report/Results/PlayerInfoGems.tsx]: Good point

File: src/interface/report/Results/PlayerInfoGems.tsx (hunk 3 above)
Comment (CericME) [reply src/interface/report/Results/PlayerInfoGems.tsx]: Wanted your opinion on this.  I'll look into the refactor.

**Comment by CericME** [comment]
Got some free time.  Here is the plan:
- Consolidate into socketBonusID the common items from GemChecker and PlayerInfoGem
- Take advantage of the empty_gem

**Comment by CericME** [comment]
Morning musing 

Should Gems have an ItemLevel stored with them as the interface for in events is 
`export interface Gem {
  id: number;
  itemLevel: number;
  icon: string;
}`

File: src/parser/core/EventsItems.ts [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+ *
+ */
+export interface GemmableSlotConfig {
+  maxSockets: number;
+  timeGated: boolean;
+  /**
+   * The id of the item used to add a socket to this slot, if it exists.
+   */
+  socketingItemId: number | undefined;
+}
```
Comment (emallson) [inline src/parser/core/EventsItems.ts]: this isn't part of `Events` but of `GemChecker` so I'd prefer it stay there.

**Review by emallson — APPROVED** [review]
refactors look good overall. minor comment about location of the `GemmableSlotConfig` interface but otherwise this is good to merge

**Comment by emallson** [comment]
> Should Gems have an ItemLevel stored with them as the interface for in events is `...`

I don't think this is currently important. They have item levels as an artifact of being items, but that is not relevant for power in any variant of wow. Relics (from Legion) have relevant ilvls but are handled differently (though I think they show up in the log as gems)

File: src/parser/core/EventsItems.ts (hunk 4 above)
Comment (CericME) [reply src/parser/core/EventsItems.ts]: I can move it back.  It's a property of the gear but there really isn't a gear item.

Comment (CericME) [reply src/parser/core/EventsItems.ts]: All moved back.
