### PR TITLE
[Marksmanship] Medallion Bug Fix

### LINKED ISSUE #640: [Marksmanship] Medallion module sometimes shows more casts than possible
Tarnished Sentinel Medallion sometimes shows "You cast X out of Y Medallion casts with trueshot." where X > Y (math degeneration, sorry 😄 ).

Example log: https://wowanalyzer.com/report/19hnvz3rNx46CHDP/20-Heroic+Maiden+of+Vigilance+-+Kill+(5:27)/Blazjoggs

### PR DESCRIPTION
**Pull request by leapis**
Resolves #640 

Bug was created when ts.end was undefined. Since TS is set length of 15 seconds, when ts.end is undefined we know that it will be (for the scope that concerns this particular module) ending at most 15 seconds later, so we can set ts.end to 15 seconds later, which resolves the bug.

### CODE REVIEW

File: src/Parser/Hunter/Marksmanship/Modules/Items/TarnishedSentinelMedallion.js [hunk 1]
```diff
@@ -36,7 +36,14 @@ class TarnishedSentinelMedallion extends ImportTarnishedSentinelMedallion {
     this.medallionUptime.forEach(cast => {
       this.medallionCasts ++;
       this.cooldownTracker.pastCooldowns.forEach(ts =>{
-        if (ts.start > cast.start - 5000 && ts.end < cast.end + 5000 && ts.spell.id === SPELLS.TRUESHOT.id){ //giving 7.5 (as agreed upon with Putro) seconds of leeway
+        let tsEnd; //because sometimes ts.end is undefined if the parser hasn't gotten there yet
+        if(!ts.end){
+          tsEnd = ts.start + 15000;
```
Comment (MartijnHols) [inline src/Parser/Hunter/Marksmanship/Modules/Items/TarnishedSentinelMedallion.js]: Please extract magic numbers to constants at the top of the file with appropriate names.

File: src/Parser/Hunter/Marksmanship/Modules/Items/TarnishedSentinelMedallion.js [hunk 2]
```diff
@@ -36,7 +36,14 @@ class TarnishedSentinelMedallion extends ImportTarnishedSentinelMedallion {
...
+        }
+        else{
+          tsEnd = ts.end;
+        }
+        if (ts.start > cast.start - 5000 && tsEnd < cast.end + 5000 && ts.spell.id === SPELLS.TRUESHOT.id){ //giving 7.5 (as agreed upon with Putro) seconds of leeway
```
Comment (MartijnHols) [inline src/Parser/Hunter/Marksmanship/Modules/Items/TarnishedSentinelMedallion.js]: Please extract magic numbers to constants at the top of the file with appropriate names.

**Comment by leapis** [comment]
Fixed
