### PR TITLE
[resto druid] ToL rewrite + some minor fixes

### LINKED ISSUE #1159: [Resto Druid] ToL prepulls  always count as a head proc

### LINKED ISSUE #1172: Clearcasting module shows over 100% clearcasting util
This fine druid was using MoC.
https://wowanalyzer.com/report/TLBp1V2ZWdhz7YJq/40-Mythic+The+Coven+of+Shivarra+-+Kill+(7:14)/Blazyb/cast-efficiency

### PR DESCRIPTION
**Pull request by kfinch**
MoC module was unable to see refreshes how I thought, switched up the display to account for this (fixes #1172 )

Innervate stat display wasn't formatted right, fixed that.

Tree of Life had some uptime tallying issues when player took both talent and legendary helm, also the module was in *desperate* need of a rewrite, so I gave it a complete rewrite and also fixed the issue while I was there (fixes #1159 ) It may be easier to look at the changes here as a new file, because it really is a full rewrite: https://github.com/kfinch/WoWAnalyzer/blob/038878f90290691d8e835c710f96704592f7b32a/src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js

### CODE REVIEW

File: src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js [hunk 1]
```diff
@@ -35,205 +44,146 @@ class TreeOfLife extends Analyzer {
...
+      if (!accumulator) {
+        return;
       }
-    }
-
-    if (SPELLS.INCARNATION_TREE_OF_LIFE_TALENT.id === spellId && (this.tolManualApplyTimestamp === null || (this.tolManualApplyTimestamp + TREE_OF_LIFE_COOLDOWN) < event.timestamp)) {
-      this.tolManualApplyTimestamp = event.timestamp;
-      this.tolCasts += 1;
-      this.proccs -= 1;
+      accumulator.rejuvManaSaved += REJUV_MANA_SAVED;
```
Comment (buimichael) [inline src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js]: Should have reductions to this variable if the user didn't make use of the extra mana saved. We have these kind of calculations on promises and carafe module.

File: src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js [hunk 2]
```diff
@@ -35,205 +44,146 @@ class TreeOfLife extends Analyzer {
...
+  _getTotalHealing(accumulator) {
+    return accumulator.allBoostHealing + accumulator.rejuvBoostHealing + accumulator.extraWgHealing + this._getManaSavedHealing(accumulator);
   }
 
   get suggestionThresholds() {
     return {
-      actual: this.totalThroughputPercent,
+      actual: this.owner.getPercentageOfTotalHealingDone(this._getTotalHealing(this.hardcast)),
       isLessThan: {
         minor: 0.11,
```
Comment (buimichael) [inline src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js]: I think we can lower the thresholds, this was more a thing in nighthold where cultivation used to easily do over 11%. I'd say minor : 0.08, average 0.06 and major 0.04 would be appropriate.

File: src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js (hunk 1 above)
Comment (kfinch) [reply src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js]: I'll take a look

File: src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js (hunk 2 above)
Comment (kfinch) [reply src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js]: yeah you're right, worth rethinking for sure

**Comment by kfinch** [comment]
Showed the mana stuff like this now: 
chameleon-song-tooltip

**Comment by kfinch** [comment]
@buimichael anyway, checkout the fixes, this what you looking for?

File: src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js (hunk 2 above)
Comment (kfinch) [reply src/Parser/Druid/Restoration/Modules/Talents/TreeOfLife.js]: Ended up doing 0.09, 0.06, 0.03, because I'm doing a thing where "minor issue is anything other than really good", "major issue is really bad".

**Comment by kfinch** [comment]
ok I don't think he checks this much to review it again, so but I resolved the issues so I'm going to merge this....
